/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const COLORS = {
  // generated by expo
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
  },
  // end generated by expo
  // chrome extension colors
  transparent: 'transparent',
  inherit: 'inherit',
  white: '#F2F2FA',
  grey: {
    DEFAULT: '#D5D5E0',
    dark: '#6F7078',
  },
  'neutral-1': '#A2A2AA',
  'neutral-2': 'rgba(255, 255, 255, 0.06)',
  'neutral-3': 'rgba(82, 82, 90, 1)',
  'neutral-4': 'rgba(255, 255, 255, 0.09)',
  black: 'rgba(24, 24, 27, 1)',
  success: {
    DEFAULT: '#3FDBA8',
    dark: '#048A4E',
    darker: '#2D403A',
    light: '#00C896',
  },
  warning: {
    DEFAULT: '#D9B32E',
    dark: '#9C791C',
  },
  error: {
    DEFAULT: '#F75363',
    dark: '#9C0A36',
    light: '#FC2A58',
  },
  blue: {
    DEFAULT: '#61CBF4',
    darker: '#43ADD6',
    dark: '#2F99C2',
    light: '#4AB8D9',
    pressed: '#117BA4',
    hover: 'rgba(10, 103, 144, 0.42)',
    'pressed-secondary': 'rgba(0, 103, 144, 0.18)',
    'hover-secondary': 'rgba(87, 193, 234, 0.18)',
  },
  background: {
    black: 'rgba(10, 9, 13, 1)',
    'dark-grey': 'rgba(24, 24, 27, 1)',
    app: 'rgba(24, 24, 27, 1)',
    'dialog-overlay': 'rgba(19, 19, 19, 0.88)',
    'dialog-bg': 'rgba(34, 34, 37, 1)',
    'dropdown-bg': 'rgb(41 41 43)',
    gradient:
      'linear-gradient(159.61deg, #202022 13.58%, rgba(51, 51, 70, 0.32) 86.49%)',
  },
  // end chrome extension colors
};
