export const ENV = {
  ENVIRONMENT_TYPE: process.env.EXPO_PUBLIC_ENVIRONMENT_TYPE,
  PROXY_SERVER_URL: process.env.EXPO_PUBLIC_PROXY_SERVER_URL,
  WALLETCONNECT_PROJECT_ID: process.env.EXPO_PUBLIC_WALLETCONNECT_PROJECT_ID,
};
